name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # - name: Build and install from an sdist # install from sdist so we know the MAINFEST.in is right
    #   run: |
    #     python setup.py sdist
    #     pip install dist/your_package_name-0.1.0.tar.gz[test]
    - name: Install
      run: |
        pip install -e .[test]
    - name: Test
      run: |
        pytest --ignore-glob='*_benchmark.py'
